-- MySQL Script generated by MySQL Workbench
-- Fri Jan 17 17:15:25 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema university.db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema university.db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `university.db` DEFAULT CHARACTER SET utf8 ;
USE `university.db` ;

-- -----------------------------------------------------
-- Table `university.db`.`universities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `university.db`.`universities` (
  `id` SMALLINT(32) UNSIGNED NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `address` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `university.db`.`faculties`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `university.db`.`faculties` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `university_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_faculty_university_idx` (`university_id` ASC) VISIBLE,
  CONSTRAINT `fk_faculty_university`
    FOREIGN KEY (`university_id`)
    REFERENCES `university.db`.`universities` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `university.db`.`departments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `university.db`.`departments` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `faculty_id` INT UNSIGNED NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_department_faculty1_idx` (`faculty_id` ASC) VISIBLE,
  CONSTRAINT `fk_department_faculty1`
    FOREIGN KEY (`faculty_id`)
    REFERENCES `university.db`.`faculties` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `university.db`.`persons`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `university.db`.`persons` (
  `id` BIGINT(32) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `university.db`.`instructors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `university.db`.`instructors` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `persons_id` BIGINT(32) UNSIGNED NOT NULL,
  `departments_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_instructors_departments1_idx` (`departments_id` ASC) VISIBLE,
  INDEX `fk_instructors_persons1_idx` (`persons_id` ASC) VISIBLE,
  CONSTRAINT `fk_instructors_persons1`
    FOREIGN KEY (`persons_id`)
    REFERENCES `university.db`.`persons` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_instructors_departments1`
    FOREIGN KEY (`departments_id`)
    REFERENCES `university.db`.`departments` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `university.db`.`courses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `university.db`.`courses` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `code` INT UNSIGNED NOT NULL,
  `department_id` INT UNSIGNED NULL,
  `instructors_id` INT UNSIGNED NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `code_UNIQUE` (`code` ASC) VISIBLE,
  INDEX `fk_course_department1_idx` (`department_id` ASC) VISIBLE,
  INDEX `fk_courses_instructors1_idx` (`instructors_id` ASC) VISIBLE,
  CONSTRAINT `fk_course_department1`
    FOREIGN KEY (`department_id`)
    REFERENCES `university.db`.`departments` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_courses_instructors1`
    FOREIGN KEY (`instructors_id`)
    REFERENCES `university.db`.`instructors` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `university.db`.`students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `university.db`.`students` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `yearOfReceipt` DATE NOT NULL,
  `major` VARCHAR(45) NOT NULL,
  `persons_id` BIGINT(32) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_students_persons1_idx` (`persons_id` ASC) VISIBLE,
  CONSTRAINT `fk_students_persons1`
    FOREIGN KEY (`persons_id`)
    REFERENCES `university.db`.`persons` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `university.db`.`administrators`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `university.db`.`administrators` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `position` VARCHAR(45) NOT NULL,
  `persons_id` BIGINT(32) UNSIGNED NOT NULL,
  `departments_id` INT UNSIGNED NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_administrators_persons1_idx` (`persons_id` ASC) VISIBLE,
  INDEX `fk_administrators_departments1_idx` (`departments_id` ASC) VISIBLE,
  CONSTRAINT `fk_administrators_persons1`
    FOREIGN KEY (`persons_id`)
    REFERENCES `university.db`.`persons` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_administrators_departments1`
    FOREIGN KEY (`departments_id`)
    REFERENCES `university.db`.`departments` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `university.db`.`grades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `university.db`.`grades` (
  `id` BIGINT(32) UNSIGNED NOT NULL AUTO_INCREMENT,
  `value` SMALLINT(32) UNSIGNED NOT NULL,
  `students_id` INT UNSIGNED NOT NULL,
  `courses_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_grades_students1_idx` (`students_id` ASC) VISIBLE,
  INDEX `fk_grades_courses1_idx` (`courses_id` ASC) VISIBLE,
  CONSTRAINT `fk_grades_students1`
    FOREIGN KEY (`students_id`)
    REFERENCES `university.db`.`students` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_grades_courses1`
    FOREIGN KEY (`courses_id`)
    REFERENCES `university.db`.`courses` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `university.db`.`schedules`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `university.db`.`schedules` (
  `id` BIGINT(32) UNSIGNED NOT NULL AUTO_INCREMENT,
  `date` DATE NOT NULL,
  `time` TIME NOT NULL,
  `courses_id` INT UNSIGNED NOT NULL,
  `students_id` INT UNSIGNED NOT NULL,
  `instructors_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `students_id`, `instructors_id`),
  INDEX `fk_schedules_courses1_idx` (`courses_id` ASC) VISIBLE,
  INDEX `fk_schedules_students1_idx` (`students_id` ASC) VISIBLE,
  INDEX `fk_schedules_instructors1_idx` (`instructors_id` ASC) VISIBLE,
  CONSTRAINT `fk_schedules_courses1`
    FOREIGN KEY (`courses_id`)
    REFERENCES `university.db`.`courses` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_schedules_students1`
    FOREIGN KEY (`students_id`)
    REFERENCES `university.db`.`students` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_schedules_instructors1`
    FOREIGN KEY (`instructors_id`)
    REFERENCES `university.db`.`instructors` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `university.db`.`student_courses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `university.db`.`student_courses` (
  `students_id` INT UNSIGNED NOT NULL,
  `courses_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`students_id`, `courses_id`),
  INDEX `fk_students_has_courses_courses1_idx` (`courses_id` ASC) VISIBLE,
  INDEX `fk_students_has_courses_students1_idx` (`students_id` ASC) VISIBLE,
  CONSTRAINT `fk_students_has_courses_students1`
    FOREIGN KEY (`students_id`)
    REFERENCES `university.db`.`students` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_students_has_courses_courses1`
    FOREIGN KEY (`courses_id`)
    REFERENCES `university.db`.`courses` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
